name = "ComplexAnalysis"
version = "0.1.0"
defaultTargets = ["complexanalysis"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ComplexAnalysis"
roots = ["ComplexAnalysis", "Basic", "BrennanConjecture", "CauchyRiemann", "R2", "Sarason", "Contour", "Laplace", "Zeta"]

[[lean_exe]]
name = "complexanalysis"
root = "Main"
