-- Auto-generated by FunSearch
import Snakey.SnakeyStrategy

open SnakeyStrategy

namespace SnakeyProof

/-- Machine-transpiled StrategyTree from FunSearch --/
def snaky_winning_tree : StrategyTree :=
  .move (0, 0) fun b =>
    if b = (1, 0) then
      .move (0, -1) fun b =>
        if b = (1, -1) then
          .move (0, 1) fun b =>
            if b = (1, 1) then
              .move (-1, 1) fun b =>
                if b = (-2, 1) then
                  .move (0, -2) fun b =>
                    if b = (1, -2) then
                      .move (-1, 0) fun b =>
                        if b = (-2, 0) then
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (-1, -2) fun b =>
                                    if b = (-2, -2) then
                                      .move (0, 2) fun b =>
                                        if b = (1, 2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                                else
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (-1, 2) fun b =>
                                        if b = (-2, -1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                        else
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (-1, -2) fun b =>
                                    if b = (-2, -2) then
                                      .move (-1, -3) fun b =>
                                        if b = (-2, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                                else
                                  .move (-1, -2) fun b =>
                                    if b = (-2, -2) then
                                      .move (-1, -3) fun b =>
                                        if b = (-2, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                    else
                      .move (1, -2) fun _ =>
                        .win
                else
                  .move (0, -2) fun b =>
                    if b = (1, -2) then
                      .move (-1, 0) fun b =>
                        if b = (-2, 0) then
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (-1, -2) fun b =>
                                    if b = (-2, 1) then
                                      .move (-2, -2) fun _ =>
                                        .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                                else
                                  .move (-1, -2) fun b =>
                                    if b = (-2, 1) then
                                      .move (-2, -2) fun _ =>
                                        .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                        else
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (-1, -2) fun b =>
                                    if b = (-2, 1) then
                                      .move (-2, -2) fun _ =>
                                        .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                                else
                                  .move (-1, -2) fun b =>
                                    if b = (-2, 1) then
                                      .move (-2, -2) fun _ =>
                                        .win
                                    else
                                      .move (-2, -2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                    else
                      .move (1, -2) fun _ =>
                        .win
            else
              .move (0, -2) fun b =>
                if b = (1, -2) then
                  .move (1, 1) fun b =>
                    if b = (-1, -2) then
                      .move (-1, 0) fun b =>
                        if b = (-2, 0) then
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                                else
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                        else
                          .move (0, -3) fun b =>
                            if b = (1, -3) then
                              .move (-1, -1) fun b =>
                                if b = (-2, -1) then
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                                else
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                    else
                      .move (-1, -2) fun _ =>
                        .win
                else
                  .move (-1, 1) fun b =>
                    if b = (1, -2) then
                      .move (1, 1) fun b =>
                        if b = (-1, -2) then
                          .move (2, 1) fun b =>
                            if b = (3, 1) then
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, -1) fun b =>
                                        if b = (-2, 2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                            else
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, -1) fun b =>
                                        if b = (-2, 2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                        else
                          .move (-1, -2) fun _ =>
                            .win
                    else
                      .move (1, -2) fun _ =>
                        .win
        else
          .move (0, 1) fun b =>
            if b = (1, 1) then
              .move (0, 2) fun b =>
                if b = (1, 2) then
                  .move (1, -1) fun b =>
                    if b = (-1, 2) then
                      .move (-1, 0) fun b =>
                        if b = (-2, 0) then
                          .move (0, 3) fun b =>
                            if b = (1, 3) then
                              .move (-1, 1) fun b =>
                                if b = (-2, 1) then
                                  .move (0, -2) fun b =>
                                    if b = (1, -2) then
                                      .move (0, -3) fun b =>
                                        if b = (1, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, -2) fun _ =>
                                        .win
                                else
                                  .move (0, -2) fun b =>
                                    if b = (1, -2) then
                                      .move (0, -3) fun b =>
                                        if b = (1, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, -2) fun _ =>
                                        .win
                            else
                              .move (1, 3) fun _ =>
                                .win
                        else
                          .move (0, 3) fun b =>
                            if b = (1, 3) then
                              .move (-1, 1) fun b =>
                                if b = (-2, 1) then
                                  .move (0, -2) fun b =>
                                    if b = (1, -2) then
                                      .move (0, -3) fun b =>
                                        if b = (1, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, -2) fun _ =>
                                        .win
                                else
                                  .move (0, -2) fun b =>
                                    if b = (1, -2) then
                                      .move (0, -3) fun b =>
                                        if b = (1, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, -2) fun _ =>
                                        .win
                            else
                              .move (1, 3) fun _ =>
                                .win
                    else
                      .move (-1, 2) fun _ =>
                        .win
                else
                  .move (-1, -1) fun b =>
                    if b = (1, 2) then
                      .move (1, -1) fun b =>
                        if b = (-1, 2) then
                          .move (2, -1) fun b =>
                            if b = (3, -1) then
                              .move (-1, 0) fun b =>
                                if b = (2, -2) then
                                  .move (-1, -2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, 1) fun b =>
                                        if b = (-2, -2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, -2) fun _ =>
                                    .win
                            else
                              .move (-1, 0) fun b =>
                                if b = (2, -2) then
                                  .move (-1, -2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, 1) fun b =>
                                        if b = (-2, -2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, -2) fun _ =>
                                    .win
                        else
                          .move (-1, 2) fun _ =>
                            .win
                    else
                      .move (1, 2) fun _ =>
                        .win
            else
              .move (0, -2) fun b =>
                if b = (1, -2) then
                  .move (-1, -2) fun b =>
                    if b = (1, 1) then
                      .move (0, 2) fun b =>
                        if b = (1, 2) then
                          .move (1, -1) fun b =>
                            if b = (-1, 2) then
                              .move (2, -1) fun b =>
                                if b = (3, -1) then
                                  .move (-1, -1) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, 0) fun b =>
                                        if b = (2, -2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (3, -1) fun b =>
                                    if b = (3, 0) then
                                      .move (3, -2) fun _ =>
                                        .win
                                    else
                                      .move (3, 0) fun _ =>
                                        .win
                            else
                              .move (-1, 2) fun _ =>
                                .win
                        else
                          .move (-1, -1) fun b =>
                            if b = (1, 2) then
                              .move (1, -1) fun b =>
                                if b = (-1, 2) then
                                  .move (2, -1) fun b =>
                                    if b = (2, 0) then
                                      .move (3, -1) fun b =>
                                        if b = (3, 0) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (-1, 2) fun _ =>
                                    .win
                            else
                              .move (1, 2) fun _ =>
                                .win
                    else
                      .move (1, 1) fun _ =>
                        .win
                else
                  .move (-1, 1) fun b =>
                    if b = (1, -2) then
                      .move (1, 1) fun b =>
                        if b = (-1, -2) then
                          .move (2, 1) fun b =>
                            if b = (3, 1) then
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (0, 2) fun b =>
                                        if b = (1, -1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                            else
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (0, 2) fun b =>
                                        if b = (1, -1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                        else
                          .move (-1, -2) fun _ =>
                            .win
                    else
                      .move (1, -2) fun _ =>
                        .win
    else
      .move (0, -1) fun b =>
        if b = (1, -1) then
          .move (0, -2) fun b =>
            if b = (1, -2) then
              .move (0, -3) fun b =>
                if b = (1, -3) then
                  .move (1, 0) fun b =>
                    if b = (-1, -3) then
                      .move (-1, -1) fun b =>
                        if b = (-2, -1) then
                          .move (1, -4) fun b =>
                            if b = (0, -4) then
                              .move (0, 1) fun b =>
                                if b = (1, 1) then
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (-1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                                else
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (-1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                            else
                              .move (0, -4) fun _ =>
                                .win
                        else
                          .move (1, -4) fun b =>
                            if b = (0, -4) then
                              .move (0, 1) fun b =>
                                if b = (1, 1) then
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (-1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                                else
                                  .move (0, 2) fun b =>
                                    if b = (1, 2) then
                                      .move (0, 3) fun b =>
                                        if b = (-1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (1, 2) fun _ =>
                                        .win
                            else
                              .move (0, -4) fun _ =>
                                .win
                    else
                      .move (-1, -3) fun _ =>
                        .win
                else
                  .move (-1, 0) fun b =>
                    if b = (1, -3) then
                      .move (1, 0) fun b =>
                        if b = (-1, -3) then
                          .move (2, 0) fun b =>
                            if b = (3, 0) then
                              .move (-1, -1) fun b =>
                                if b = (2, 1) then
                                  .move (-1, 1) fun b =>
                                    if b = (2, -1) then
                                      .move (-1, -2) fun b =>
                                        if b = (-2, 1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, -1) fun _ =>
                                        .win
                                else
                                  .move (2, 1) fun _ =>
                                    .win
                            else
                              .move (-1, -1) fun b =>
                                if b = (2, 1) then
                                  .move (-1, 1) fun b =>
                                    if b = (2, -1) then
                                      .move (-1, -2) fun b =>
                                        if b = (-2, 1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, -1) fun _ =>
                                        .win
                                else
                                  .move (2, 1) fun _ =>
                                    .win
                        else
                          .move (-1, -3) fun _ =>
                            .win
                    else
                      .move (1, -3) fun _ =>
                        .win
            else
              .move (0, 1) fun b =>
                if b = (1, 1) then
                  .move (-1, 1) fun b =>
                    if b = (1, -2) then
                      .move (0, -3) fun b =>
                        if b = (1, -3) then
                          .move (1, 0) fun b =>
                            if b = (-1, -3) then
                              .move (2, 0) fun b =>
                                if b = (3, 0) then
                                  .move (-1, 0) fun b =>
                                    if b = (2, -1) then
                                      .move (-1, -1) fun b =>
                                        if b = (2, 1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, -1) fun _ =>
                                        .win
                                else
                                  .move (3, 0) fun b =>
                                    if b = (3, -1) then
                                      .move (3, 1) fun _ =>
                                        .win
                                    else
                                      .move (3, -1) fun _ =>
                                        .win
                            else
                              .move (-1, -3) fun _ =>
                                .win
                        else
                          .move (-1, 0) fun b =>
                            if b = (1, -3) then
                              .move (1, 0) fun b =>
                                if b = (-1, -3) then
                                  .move (2, 0) fun b =>
                                    if b = (2, -1) then
                                      .move (3, 0) fun b =>
                                        if b = (3, -1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, -1) fun _ =>
                                        .win
                                else
                                  .move (-1, -3) fun _ =>
                                    .win
                            else
                              .move (1, -3) fun _ =>
                                .win
                    else
                      .move (1, -2) fun _ =>
                        .win
                else
                  .move (-1, 1) fun b =>
                    if b = (1, -2) then
                      .move (1, 1) fun b =>
                        if b = (-1, -2) then
                          .move (2, 1) fun b =>
                            if b = (3, 1) then
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, -1) fun b =>
                                        if b = (-2, 2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                            else
                              .move (-1, 0) fun b =>
                                if b = (2, 2) then
                                  .move (-1, 2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, -1) fun b =>
                                        if b = (-2, 2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, 2) fun _ =>
                                    .win
                        else
                          .move (-1, -2) fun _ =>
                            .win
                    else
                      .move (1, -2) fun _ =>
                        .win
        else
          .move (0, 1) fun b =>
            if b = (1, 1) then
              .move (0, 2) fun b =>
                if b = (1, 2) then
                  .move (1, -1) fun b =>
                    if b = (-1, 2) then
                      .move (0, 3) fun b =>
                        if b = (1, 3) then
                          .move (1, 0) fun b =>
                            if b = (-1, 3) then
                              .move (2, 0) fun b =>
                                if b = (3, 0) then
                                  .move (2, -1) fun b =>
                                    if b = (3, -1) then
                                      .move (-1, 0) fun b =>
                                        if b = (-1, 1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-1, 0) fun b =>
                                        if b = (-1, 1) then
                                          .win
                                        else
                                          .win
                                else
                                  .move (3, 0) fun b =>
                                    if b = (3, -1) then
                                      .move (3, 1) fun _ =>
                                        .win
                                    else
                                      .move (3, -1) fun _ =>
                                        .win
                            else
                              .move (-1, 3) fun _ =>
                                .win
                        else
                          .move (1, 0) fun b =>
                            if b = (-1, 3) then
                              .move (-1, 0) fun b =>
                                if b = (1, 3) then
                                  .move (-2, 0) fun b =>
                                    if b = (-2, 1) then
                                      .move (-3, 0) fun b =>
                                        if b = (-3, -1) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-2, 1) fun _ =>
                                        .win
                                else
                                  .move (1, 3) fun _ =>
                                    .win
                            else
                              .move (-1, 3) fun _ =>
                                .win
                    else
                      .move (-1, 2) fun _ =>
                        .win
                else
                  .move (-1, -1) fun b =>
                    if b = (1, 2) then
                      .move (1, -1) fun b =>
                        if b = (-1, 2) then
                          .move (2, -1) fun b =>
                            if b = (3, -1) then
                              .move (-1, 0) fun b =>
                                if b = (2, -2) then
                                  .move (-1, -2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, 1) fun b =>
                                        if b = (-2, -2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, -2) fun _ =>
                                    .win
                            else
                              .move (-1, 0) fun b =>
                                if b = (2, -2) then
                                  .move (-1, -2) fun b =>
                                    if b = (2, 0) then
                                      .move (-1, 1) fun b =>
                                        if b = (-2, -2) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (2, 0) fun _ =>
                                        .win
                                else
                                  .move (2, -2) fun _ =>
                                    .win
                        else
                          .move (-1, 2) fun _ =>
                            .win
                    else
                      .move (1, 2) fun _ =>
                        .win
            else
              .move (0, -2) fun b =>
                if b = (1, -2) then
                  .move (1, 1) fun b =>
                    if b = (-1, -2) then
                      .move (0, 2) fun b =>
                        if b = (1, 2) then
                          .move (1, -1) fun b =>
                            if b = (-1, 2) then
                              .move (0, -3) fun b =>
                                if b = (1, -3) then
                                  .move (1, 0) fun b =>
                                    if b = (-1, -3) then
                                      .move (0, 3) fun b =>
                                        if b = (-1, 3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-1, -3) fun _ =>
                                        .win
                                else
                                  .move (1, 0) fun b =>
                                    if b = (-1, -3) then
                                      .move (-1, 0) fun b =>
                                        if b = (1, -3) then
                                          .win
                                        else
                                          .win
                                    else
                                      .move (-1, -3) fun _ =>
                                        .win
                            else
                              .move (-1, 2) fun _ =>
                                .win
                        else
                          .move (1, 2) fun b =>
                            if b = (-1, -1) then
                              .move (1, -1) fun b =>
                                if b = (-1, 2) then
                                  .move (1, 0) fun b =>
                                    if b = (2, -1) then
                                      .move (2, 2) fun _ =>
                                        .win
                                    else
                                      .move (2, -1) fun _ =>
                                        .win
                                else
                                  .move (-1, 2) fun _ =>
                                    .win
                            else
                              .move (-1, -1) fun _ =>
                                .win
                    else
                      .move (-1, -2) fun _ =>
                        .win
                else
                  .move (-1, 1) fun b =>
                    if b = (1, -2) then
                      .move (1, 1) fun b =>
                        if b = (-1, -2) then
                          .move (-2, 1) fun _ =>
                            .move (1, 0) fun b =>
                              if b = (-2, 2) then
                                .move (1, 2) fun b =>
                                  if b = (-2, 0) then
                                    .move (0, 2) fun b =>
                                      if b = (-1, -1) then
                                        .win
                                      else
                                        .win
                                  else
                                    .move (-2, 0) fun _ =>
                                      .win
                              else
                                .move (-2, 2) fun _ =>
                                  .win
                        else
                          .move (-1, -2) fun _ =>
                            .win
                    else
                      .move (1, -2) fun _ =>
                        .win

/-- Theorem: Machine-verified winning strategy for the Snaky Hexomino! -/
theorem maker_wins_snakey_verified :
  winning_strategy Snakey_base snaky_winning_tree [] [] := by
  dsimp [snaky_winning_tree, winning_strategy, Snakey_base]
  decide

end SnakeyProof
